news/urls.py
from django.urls import path
from django.conf.urls import url
from .views import NewsList, PostAuthor,PostView, PostSearch, PostCreateView, PostDeleteView, PostUpdateView ,  PostTag, PostType, subscribe_to_category, unsubscribe_from_category,ProfileView#, send_emails

app_name = 'news'
urlpatterns = [
    # path — означает путь. В данном случае путь ко всем товарам у нас останется пустым, позже станет ясно, почему
    path('', NewsList.as_view(), name='news'),  # т. к. сам по себе это класс, то нам надо представить этот класс в виде view. Для этого вызываем метод as_view
    path('<int:pk>', PostView.as_view()),
    path('post/<int:pk>', PostView.as_view(), name='post_view'),
    path('search/', PostSearch.as_view(), name='search'),
    path('search/<int:pk>', PostView.as_view()),

    path('add/', PostCreateView.as_view(), name='post_add'),  # Ссылка на создание товара

    path('<int:pk>/edit', PostUpdateView.as_view(), name='post_edit'),
    path('<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
    # url(r'^post_author$', post_author),
    path('author/<int:pk>', PostAuthor.as_view(), name='author_name'),
    path('type/<str:name>', PostType.as_view(), name='post_type'),
    path('tag/<int:pk>', PostTag.as_view(), name='post_tag'),

    path('subscribe/<int:pk>', subscribe_to_category, name='sub_cat'),
    path('unsubscribe/<int:pk>', unsubscribe_from_category, name='unsub_cat'),
    path('profile/', ProfileView.as_view(), name='profile'),

]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.utils import timezone

class Author(models.Model):
    authorUsername = models.OneToOneField(User, on_delete=models.CASCADE)
    authorRating = models.SmallIntegerField(default=0)
    avatar = models.ImageField(upload_to='static/img')
    
    def __str__(self):
        return f'{self.authorUsername}'

    def update_rating(self):
        postRate = self.post_set.all().aggregate(postRating = Sum('rating')) 
        #  postrating?
        pRate = 0
        pRate += postRate.get('postRating')

        commentRate = self.authorUsername.comment_set.all().aggregate(commentRating = Sum('rating'))
        cRate = 0
        cRate += commentRate.get('commentRating')

        self.authorRating = pRate * 3 + cRate
        self.save()

class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, through='CatSub', blank=True)
    def subscribe(self):
        pass
    def get_category(self):
        return self.name

    def __str__(self):
        return f'{self.name}' 

class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    NEWS = 'NWS'
    ARTICLE = 'ART'
    REVIEW = 'RVW'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
        (REVIEW, 'Обзор'),
    )
    categoryType = models.CharField(
        max_length=3, choices=CATEGORY_CHOICES, default=ARTICLE)

    dateCreated = models.DateTimeField(default=timezone.now)
    text = models.TextField(default='')
    title = models.CharField(max_length=128)
    rating = models.SmallIntegerField(default=0)
    isUpdated = models.BooleanField(default=False)

    postCategory = models.ManyToManyField(Category, through='PostCategory')
    
    def like(self):
        self.rating += 1 
        self.save()
    
    def dislike(self):
        self.rating -= 1 
        self.save()
    
    def preview(self):
        return f'{self.text[0:125]} ... rating: {str(self.rating)}'
      
    def email_preview(self):
        return f'{self.text[0:50]}...'
      

    def get_absolute_url(self):  # добавим абсолютный путь, чтобы после создания нас перебрасывало на страницу с товаром
        return f'/post/{self.id}' 
    
    def get_cat(self):
        return self.categoryType

    def __str__(self):
        return f'{self.dateCreated.date()} :: {self.author} :: {self.title} {self.categoryType}' 


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.categoryThrough} -> {self.postThrough}'

class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreated = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        try:
            return self.commentPost.author.username
        except:
            return self.commentUser.username

    def like(self):
        self.rating += 1 
        self.save()
    
    def dislike(self):
        self.rating -= 1 
        self.save()


class CatSub(models.Model):
    category = models.ForeignKey(Category, on_delete = models.CASCADE, blank=True, null=True)
    subscriber = models.ForeignKey(User, on_delete = models.CASCADE, blank=True, null=True)

    def get_user(self):
      return self.subscriber

    def get_category(self):
      return self.category.name
    def get_cat(self):
      return self.category

    def __str__(self):
        return f'{self.subscriber} - {self.category.name}'

news/forms.py
from django.forms import ModelForm  # Импортируем true-false поле
from django import forms

from .models import Post


# Создаём модельную форму
class PostForm(ModelForm):
    # в класс мета, как обычно, надо написать модель, по которой будет строится форма и нужные нам поля. Мы уже делали что-то похожее с фильтрами.
    class Meta:
        model = Post
        fields = [
          'categoryType', 
          'postCategory',
          'title', 
          'text' 
          ]

        widgets = {
          'categoryType' : forms.Select(attrs={'class': 'form-control pure-input-1-2'}),
          'postCategory' : forms.SelectMultiple(attrs={'class': 'form-control pure-input-1-2',   'placeholder': 'Post Category'}),
          'title' : forms.TextInput(attrs={'class': 'form-control pure-input-1-2',   'placeholder': 'Post Title'}),
          'text': forms.Textarea(attrs={'class': 'form-control pure-input-1-2'})
        }
        labels = {
                    "categoryType": "Type",
                    "postCategory": "Category",
                    "title": "Title",
                    "text": "Text",
                }

news/views.py
from datetime import timedelta
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import User
from django.core.mail import EmailMultiAlternatives  # импортируем класс для создание объекта письма с html
from django.shortcuts import redirect
from django.template.loader import render_to_string  # импортируем функцию, которая срендерит наш html в текст
from django.urls import resolve
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView

from django.utils.timezone import datetime
# импортируем недавно написанный фильтр
from .filters import C, PostFilter
from .forms import PostForm  # импортируем нашу форму
from .models import Post, Author, Category, CatSub
from django.http import HttpResponse


class NewsList(ListView):
    model = Post
    template_name = 'news/news.html'
    context_object_name = 'news'
    queryset = Post.objects.order_by('-dateCreated')
    paginate_by = 10  # поставим постраничный вывод в один элемент
    # добавляем форм класс, чтобы получать доступ к форме через метод POST
    form_class = PostForm

    # забираем отфильтрованные объекты переопределяя метод get_context_data у наследуемого класса 
    # (привет, полиморфизм, мы скучали!!!)
    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        # вписываем наш фильтр в контекст
        context['filter'] = PostFilter(
            self.request.GET, queryset=self.get_queryset())
        # context['categories'] = Category.objects.all()
        context['form'] = PostForm
        return context


class PostView(DetailView):
    model = Post
    template_name = 'news/post.html'
    context_object_name = 'post'


# дженерик для получения деталей о товаре
class PostSearch(ListView):
    template_name = 'news/search.html'
    context_object_name = 'posts'
    queryset = Post.objects.all()

    # забираем отфильтрованные объекты переопределяя метод get_context_data у наследуемого класса 
    # (привет, полиморфизм, мы скучали!!!)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # вписываем наш фильтр в контекст
        context['filter'] = PostFilter(
            self.request.GET, queryset=self.get_queryset())
        # context['categories'] = Category.objects.all()
        context['form'] = PostForm

        return context


def page_name(r):
    req = resolve(r.path_info).kwargs['name']
    # print(req)
    return req


class PostAuthor(ListView):
    model = Post
    template_name = 'news/subcat/filtered.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        self.id = resolve(self.request.path_info).kwargs['pk']
        queryset = Post.objects.filter(author=Author.objects.get(id=self.id))

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(
            self.request.GET, queryset=self.get_queryset())
        context['name'] = Author.objects.get(authorUsername=User.objects.get(id=self.id))

        return context


class PostType(ListView):
    model = Post
    template_name = 'news/subcat/filtered.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        self.name = resolve(self.request.path_info).kwargs['name']
        queryset = Post.objects.filter(categoryType=self.name)
        return queryset


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(
            self.request.GET, queryset=self.get_queryset())
        context['name'] = self.name

        return context


class PostTag(ListView):
    model = Post
    template_name = 'news/subcat/filtered.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        self.id = resolve(self.request.path_info).kwargs['pk']
        queryset = Post.objects.filter(postCategory=Category.objects.get(id=self.id))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(
            self.request.GET, queryset=self.get_queryset())
        context['name'] = Category.objects.get(id=self.id)

        return context


class PostCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'news/crud/post_create.html'
    form_class = PostForm
    success_url = '/news/'
    permission_required = ('news.add_post')
    error_message = 'You cannot post more than 3 posts a day'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = Author.objects.get(authorUsername=self.request.user)
        postAuthor = self.object.author
        posts = Post.objects.all()
        count_todays_posts = 0 
        for post in posts:
            if post.author == postAuthor:
                time_delta = datetime.now().date() - post.dateCreated.date()
                if time_delta.total_seconds() < 86400:
                    count_todays_posts +=1

        if count_todays_posts < 3:
            self.object.save()
        
            cat = Category.objects.get(pk=self.request.POST['postCategory'])
            self.object.postCategory.add(cat)

            validated = super().form_valid(form)

        else: 
            messages.error(self.request,  'You cannot post more than 3 posts a day.')
            validated = super().form_invalid(form)

        return validated

# дженерик для редактирования объекта
class PostUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'news/crud/post_create.html'
    form_class = PostForm
    success_url = '/news/'

    permission_required = ('news.change_post')

    # метод get_object мы используем вместо queryset, чтобы получить информацию об объекте, который мы собираемся редактировать
    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        post = Post.objects.get(pk=id)
        post.isUpdated = True
        return post


# дженерик для удаления товара
class PostDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'news/crud/post_delete.html'
    success_url = '/news/'
    permission_required = ('news.delete_post')

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)


class ProfileView(ListView):
    model = CatSub
    template_name = 'news/profile.html'
    context_object_name = 'categories'


# Подписка пользователя в категорию новостей
@login_required
def subscribe_to_category(request, pk):
    user = request.user
    cat = Category.objects.get(id=pk)

    if not cat.subscribers.filter(id=user.id).exists():     
        cat.subscribers.add(user)
        html = render_to_string(
            'news/subcat/subsribed.html',
            {'categories': cat, 'user': user}, # передаем в шаблон какие захотим переменные, в данном случае я просто передал категорию для вывода ее в письме
        )  
        category = f'{cat}'
        email = user.email
        msg = EmailMultiAlternatives(
            subject=f'{category} category subscription',
            from_email='newsportal@yandex.ru',
            to=[email, ],
        ) 

        msg.attach_alternative(html, 'text/html')
        try:
            msg.send()
        except Exception as e:
            print(e)
        return redirect('/news/profile/')
        

    return redirect(request.META.get('HTTP_REFERER'))

@login_required
def unsubscribe_from_category(request, pk):
    user = request.user
    cat = Category.objects.get(id=pk)

    if cat.subscribers.filter(id=user.id).exists():     
        cat.subscribers.remove(user)        
    return redirect('/news/profile/')

news/templates/news/index.html
{% extends 'news/layout.html' %}


{% block title %} Home Page {% endblock title %}

<!-- block -->

{% block content %}
<h1>
  Home Page
</h1>

{% endblock content %}

news/templates/news/layout.html
{% load static %}

{% load custom_filters %}

<!-- не забываем заранее загружать наши фильтры! -->

<html lang="en">

<head>

  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <meta name="description" content="A layout example that shows off a blog page with a list of posts." />

  <!-- Milligram CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.4.1/milligram.css">

  <link rel="stylesheet" href="https://unpkg.com/purecss@2.0.6/build/pure-min.css"
    integrity="sha384-Uu6IeWbM+gzNVXJcM9XV3SohHtmWE+3VGi496jvgX1jyvDTXfdK+rfZc8C1Aehk5" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://unpkg.com/purecss@2.0.6/build/grids-responsive-min.css" />
  <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
  <title>Django NewsPortal — {% block title %} {% endblock title %}</title>
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
</head>

<body>

  <div class="pure-g" id="layout">
    <div class="sidebar pure-u-1 pure-u-md-1-4">
      <div class="header">
        <h1 class="brand-title">News Portal</h1>
        <h2 class="brand-tagline">Creating a blog using Django and PureCSS</h2>
        <nav class="nav">
          <ul class="nav-list">
            <li class="nav-item"><a class="pure-button" href="https://www.djangoproject.com/">Django</a></li>
            <li class="nav-item"><a class="pure-button" href="http://purecss.io">Pure</a></li>
          </ul>
          <div id="menu">
            <div class="pure-menu">
              <ul class="pure-menu-list">
                <li class="pure-menu-item">
                  <a class="pure-menu-link" href="/">Home</a>
                </li>
                <li class="pure-menu-item">
                  <a class="pure-menu-link" href="{% url 'news:news' %}">News</a>
                </li>
                <li class="pure-menu-item">
                  <a class="pure-menu-link" href="{% url 'news:search' %}">Search</a>
                </li>
                <li class="pure-menu-item">
                  <a class="pure-menu-link" href="{% url 'news:post_add' %}">New Post</a>
                </li>
                {% if user.is_superuser%}
                <li class="pure-menu-item">
                  <a class="pure-menu-link" href="/admin/">Admin</a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </div>

    <div class="content pure-u-1 pure-u-md-3-4">
      <div>
        <!--  A wrapper for all the blog posts -->
        <div class="posts">
          {% block content %} {{ flatpage.content }} {% endblock content%}
        </div>
        <div class="footer">
          <div class="pure-menu pure-menu-horizontal">
            <ul>
              <li class="pure-menu-item"><a class="pure-menu-link" href="http://purecss.io/">Pure CSS</a></li>
              <li class="pure-menu-item"><a class="pure-menu-link" href="http://twitter.com/">Twitter</a></li>
              <li class="pure-menu-item"><a class="pure-menu-link" href="http://github.com/skripkalisa">GitHub</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
</body>

</html>

news/templates/news/news.html
<!--наследуемся от шаблона default.html, который мы создавали ещё во времена flatpages -->
{% extends 'news/layout.html' %}
{% load custom_filters %}
<!--   Название у нас будет  -->
{% block title %} The news {% endblock title %}
<!--   block -->
{% block content %}
<h3 class="content-subhead">
  The news
  <span>{{ news|length }}</span>
</h3>


<!-- {{news.values}} -->

{% if is_paginated %}

<!-- Если доступна предыдущая страница, то даём ссылку на неё и самую первую страницу -->
<div class="mx-auto d-flex justify-content-center">
  <div class="pure-button-group" role="group" aria-label="...">

    {% if page_obj.has_previous %}

    <a class="page-link" href="?page=1">
      <button class="pure-button button-secondary">
        First
      </button>
    </a>
    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
      <button class="pure-button button-secondary">
        &laquo;
      </button>
    </a>

    {% endif %}

    <!-- Показываем только текущую страницу и ближайшие к ней, чтобы список не тянулся и не захламлял страницу -->
    {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
    <a class="page-link" href="#">
      <button class="pure-button button-secondary pure-button-active">
        {{ num }}
      </button>
    </a>


    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %} <a class="page-link"
      href="?page={{ num }}">
      <button class="pure-button button-secondary">
        {{ num }}
      </button>
      </a>
      {% endif %}
      {% endfor %}

      <!-- Если есть следующая страница, то даём ссылку на неё и на самую последнюю страницу -->
      {% if page_obj.has_next %}
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">
        <button class="pure-button button-secondary">
          &raquo;
        </button>
      </a>

      <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
        <button class="pure-button button-secondary">
          Last
        </button>
      </a>

      {% endif %}
  </div>
</div>
{% endif %}

<!--  loop -->
{% for n in news %}

<!--  A single blog post -->
<section class="post">
  <header class="post-header"><img class="post-avatar" src="/{{  n.author.avatar }}" alt="avatar" />
    <a href="{% url 'news:post_view' n.id %}">
      <h2 class="post-title">{{n.title|censor}}</h2>
    </a>
    <p class="post-meta">By
      <a class="post-author" href="{% url 'news:author_name' n.author_id %}">
        {{ n.author }}
      </a>
      on
      <em>{{ n.dateCreated|date:'d M Y H:i' }}
      </em>
      Type:
      <a class="post-category post-type-{{n.categoryType}}" href="{% url 'news:post_type' n.categoryType %}">

        <span>
          {{n.get_categoryType_display}}
        </span>
      </a>
      Tags:
      {% for tag in n.postCategory.values %}
      <a class="post-category post-category-{{tag.id}}" href="{% url 'news:post_tag' tag.id %}">
        {{tag.name }}
      </a>
      {%endfor%}
    </p>
  </header>
  <div class="post-description">
    <p>{{ n.text|censor | truncatewords:25 }}</p>
    <p><em>Article rating: {{n.rating}} </em></p>
  </div>
</section>
<hr />
{%endfor%}



{% endblock content %}

news/templates/news/post.html
<!-- наследуемся от шаблона default.html, который мы создавали ещё во времена flatpages -->

{% extends 'news/layout.html' %}

{% load custom_filters %}
<!-- Название у нас будет proudcts -->

{% block title %} Post {% endblock title %}

{% block content %}

<a href="{% url 'news:post_edit' post.id %}">
  <button class="pure-button button-warning">

    <i class="bi bi-pencil-square"></i>
    Edit
  </button>
</a>
<a href="{% url 'news:post_delete' post.id %}">
  <button class="pure-button button-error">
    <i class="bi bi-trash"></i>
    Delete
  </button>
</a>


<section class="post">
  <header class="post-header"><img class="post-avatar" src="/{{  post.author.avatar }}" alt="avatar" />
    <h2 class="post-title">{{post.title|censor}}</h2>
    <p class="post-meta">By
      <a class="post-author" href="{% url 'news:author_name' post.author.id %}">
        <strong>
          {{ post.author }}
        </strong>
      </a>on

      <em>{{ post.dateCreated|date:'d M Y H:i'}}. </em>
      Type:
      <a class="post-category post-type-{{post.categoryType}}" href="{% url 'news:post_type' post.categoryType %}">
        {{post.get_categoryType_display}}
      </a>
      Tags:
      {%for tag in post.postCategory.values%}
      <a class="post-category post-category-{{tag.id}}" href="{% url 'news:post_tag' tag.id %}">
        {{tag.name}}</a>
      </a>
      {%endfor%}
      <span>
        Author rating: {{post.author.authorRating}}
      </span>
    </p>
  </header>
  <div class="post-description">
    <p>{{ post.text|censor }}</p>
    <p>Likes: <em>{{ post.rating }}</em></p>
  </div>



  <div class="comments">
    <h3 class="comment-heading">Comments:</h3>
    {% if post.comment_set.all %}
    {% for comment in post.comment_set.all %}
    <div class="comment-wrapper">
      <div class="comment">
        <p class="comment-text">{{ comment.text|censor }} </p>
        <p>Likes: {{ comment.rating }}</p>
        <p class="comment-info">Comment author:
          <b>{{ comment.commentUser.username }} </b><span>on </span>
          <em>{{ comment.dateCreated|date:'d M Y' }} </em>
        </p>
      </div><img class="comment-avatar" src="/{{  comment.commentUser.author.avatar }}" alt="avatar" />
    </div>
    <hr />
    {% endfor %}
    {% else %}
    <p class="comment-heading">No comments yet.</p>
    {% endif %}
  </div>
</section>
{% endblock content %}

news/templates/news/profile.html
{% extends "news/layout.html" %}

{% block content %}
<h2>Страница авторизованного пользователя
  <strong>
    {{request.user.username}}
  </strong>
</h2>
<div>
  You have successfully subscribed to:
  <ul>

    {% for category in categories%}
    {% if request.user == category.get_user %}
    <li>
      {{category.get_category}}
      <a href="{% url 'news:unsub_cat' category.get_cat.id %}">
        <button class="button-xsmall pure-button button-warning">
          <i class="bi bi-bookmark-plus"></i>
          Unsubscribe
        </button>
      </a>
    </li>
    {%endif%}
    {%endfor%}
  </ul>
</div>

{% if is_not_authors %}

<p>
  If you want to be an author and post in this blog, press the button below
</p>
<a href="{% url 'sign:upgrade' %}">
  <button class="button-warning pure-button">
    Make me an Author!
  </button>
</a>
{% endif %}

<a href="{% url 'sign:logout'}">
  <button class="button-primary pure-button">
    Выйти
  </button>
</a>
{% endblock %}

news/templates/news/search.html
{% extends 'news/layout.html' %}
{% load custom_filters %}
<!--   Название у нас будет  -->
{% block title %} The news {% endblock title %}
<!--   block -->
{% block content %}
<h3 class="content-subhead">
  Total Posts
  <span>{{ posts|length }}</span>
</h3>
<!-- Перед таблицей добавим форму для поиска -->
<form class="pure-form" method="GET">
  <fieldset>

    {{ filter.form }}
    <!-- Форму от фильтров за нас сделает django. А вот кнопку, увы придётся делать самому -->
  </fieldset>

  <button class="pure-button button-secondary">
    Найти
  </button>
</form>
<!--  loop -->
<p>
  {{filter.categoryType}}
</p>
<p>
  {{filter.qs.categoryType }}
</p>
{% if filter == null %}
<h3>
  no posts
</h3>
{%else%}
<h3 class="content-subhead">
  Posts Found
  <span>{{ filter.qs|length }}</span>
</h3>
{% for n in filter.qs %}
<!--  A single blog post -->
<section class="post">
  <header class="post-header"><img class="post-avatar" src="/{{  n.author.avatar }}" alt="avatar" />
    <a href="{% url 'news:post_view' n.id%}">
      <h2 class="post-title">{{n.title|censor}}</h2>
    </a>
    <p class="post-meta">By
      <a class="post-author" href="{% url 'news:author_name' n.author.id%}">
        {{ n.author.authorUsername }}
      </a>
      on
      <i>{{ n.dateCreated|date:'d M Y H:i' }}
      </i>
      Type:
      <a class="post-category post-type-{{n.categoryType}}" href="{% url 'news:post_type' n.categoryType %}">
        <span>
          {{n.get_categoryType_display}}
        </span>
      </a>
      Tags:
      {% for tag in n.postCategory.values %}
      <a class="post-category post-category-{{tag.id}}" href="{% url 'news:post_tag' tag.id %}">
        {{tag.name }}
      </a>
      {%endfor%}

    </p>
  </header>
  <div class="post-description">
    <p>{{ n.text|censor | truncatewords:25 }}</p>
    <p><em>Article rating: {{n.rating}} </em></p>
  </div>
</section>
<hr />
{%endfor%}
{%endif%}

{% endblock content %}