news/urls.py
from django.urls import path
from django.conf.urls import url
from .views import NewsList, PostAuthor,PostView, PostSearch, PostCreateView, PostDeleteView, PostUpdateView ,  PostTag, PostType, subscribe_to_category, unsubscribe_from_category,ProfileView#, send_emails

app_name = 'news'
urlpatterns = [
    # path — означает путь. В данном случае путь ко всем товарам у нас останется пустым, позже станет ясно, почему
    path('', NewsList.as_view(), name='news'),  # т. к. сам по себе это класс, то нам надо представить этот класс в виде view. Для этого вызываем метод as_view
    path('<int:pk>', PostView.as_view()),
    path('post/<int:pk>', PostView.as_view(), name='post_view'),
    path('search/', PostSearch.as_view(), name='search'),
    path('search/<int:pk>', PostView.as_view()),

    path('add/', PostCreateView.as_view(), name='post_add'),  # Ссылка на создание товара

    path('<int:pk>/edit', PostUpdateView.as_view(), name='post_edit'),
    path('<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
    # url(r'^post_author$', post_author),
    path('author/<int:pk>', PostAuthor.as_view(), name='author_name'),
    path('type/<str:name>', PostType.as_view(), name='post_type'),
    path('tag/<int:pk>', PostTag.as_view(), name='post_tag'),

    path('subscribe/<int:pk>', subscribe_to_category, name='sub_cat'),
    path('unsubscribe/<int:pk>', unsubscribe_from_category, name='unsub_cat'),
    path('profile/', ProfileView.as_view(), name='profile'),

]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.utils import timezone

class Author(models.Model):
    authorUsername = models.OneToOneField(User, on_delete=models.CASCADE)
    authorRating = models.SmallIntegerField(default=0)
    avatar = models.ImageField(upload_to='static/img')
    
    def __str__(self):
        return f'{self.authorUsername}'

    def update_rating(self):
        postRate = self.post_set.all().aggregate(postRating = Sum('rating')) 
        #  postrating?
        pRate = 0
        pRate += postRate.get('postRating')

        commentRate = self.authorUsername.comment_set.all().aggregate(commentRating = Sum('rating'))
        cRate = 0
        cRate += commentRate.get('commentRating')

        self.authorRating = pRate * 3 + cRate
        self.save()

class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, through='CatSub', blank=True)
    def subscribe(self):
        pass
    def get_category(self):
        return self.name

    def __str__(self):
        return f'{self.name}' 

class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    NEWS = 'NWS'
    ARTICLE = 'ART'
    REVIEW = 'RVW'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
        (REVIEW, 'Обзор'),
    )
    categoryType = models.CharField(
        max_length=3, choices=CATEGORY_CHOICES, default=ARTICLE)

    dateCreated = models.DateTimeField(default=timezone.now)
    text = models.TextField(default='')
    title = models.CharField(max_length=128)
    rating = models.SmallIntegerField(default=0)
    isUpdated = models.BooleanField(default=False)

    postCategory = models.ManyToManyField(Category, through='PostCategory')
    
    def like(self):
        self.rating += 1 
        self.save()
    
    def dislike(self):
        self.rating -= 1 
        self.save()
    
    def preview(self):
        return f'{self.text[0:125]} ... rating: {str(self.rating)}'
      
    def email_preview(self):
        return f'{self.text[0:50]}...'
      

    def get_absolute_url(self):  # добавим абсолютный путь, чтобы после создания нас перебрасывало на страницу с товаром
        return f'/post/{self.id}' 
    
    def get_cat(self):
        return self.categoryType

    def __str__(self):
        return f'{self.dateCreated.date()} :: {self.author} :: {self.title} {self.categoryType}' 


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.categoryThrough} -> {self.postThrough}'

class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreated = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        try:
            return self.commentPost.author.username
        except:
            return self.commentUser.username

    def like(self):
        self.rating += 1 
        self.save()
    
    def dislike(self):
        self.rating -= 1 
        self.save()


class CatSub(models.Model):
    category = models.ForeignKey(Category, on_delete = models.CASCADE, blank=True, null=True)
    subscriber = models.ForeignKey(User, on_delete = models.CASCADE, blank=True, null=True)

    def get_user(self):
      return self.subscriber

    def get_category(self):
      return self.category.name
    def get_cat(self):
      return self.category

    def __str__(self):
        return f'{self.subscriber} - {self.category.name}'

news/forms.py
from django.forms import ModelForm  # Импортируем true-false поле
from django import forms

from .models import Post


# Создаём модельную форму
class PostForm(ModelForm):
    # в класс мета, как обычно, надо написать модель, по которой будет строится форма и нужные нам поля. Мы уже делали что-то похожее с фильтрами.
    class Meta:
        model = Post
        fields = [
          'categoryType', 
          'postCategory',
          'title', 
          'text' 
          ]

        widgets = {
          'categoryType' : forms.Select(attrs={'class': 'form-control pure-input-1-2'}),
          'postCategory' : forms.SelectMultiple(attrs={'class': 'form-control pure-input-1-2',   'placeholder': 'Post Category'}),
          'title' : forms.TextInput(attrs={'class': 'form-control pure-input-1-2',   'placeholder': 'Post Title'}),
          'text': forms.Textarea(attrs={'class': 'form-control pure-input-1-2'})
        }
        labels = {
                    "categoryType": "Type",
                    "postCategory": "Category",
                    "title": "Title",
                    "text": "Text",
                }

news/views.py
from datetime import timedelta
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import User
from django.core.mail import EmailMultiAlternatives  # импортируем класс для создание объекта письма с html
from django.shortcuts import redirect
from django.template.loader import render_to_string  # импортируем функцию, которая срендерит наш html в текст
from django.urls import resolve
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView

from django.utils.timezone import datetime
# импортируем недавно написанный фильтр
from .filters import C, PostFilter
from .forms import PostForm  # импортируем нашу форму
from .models import Post, Author, Category, CatSub
from django.http import HttpResponse


class NewsList(ListView):
    model = Post
    template_name = 'news/news.html'
    context_object_name = 'news'
    queryset = Post.objects.order_by('-dateCreated')
    paginate_by = 10  # поставим постраничный вывод в один элемент
    # добавляем форм класс, чтобы получать доступ к форме через метод POST
    form_class = PostForm

    # забираем отфильтрованные объекты переопределяя метод get_context_data у наследуемого класса 
    # (привет, полиморфизм, мы скучали!!!)
    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        # вписываем наш фильтр в контекст
        context['filter'] = PostFilter(
            self.request.GET, queryset=self.get_queryset())
        # context['categories'] = Category.objects.all()
        context['form'] = PostForm
        return context


class PostView(DetailView):
    model = Post
    template_name = 'news/post.html'
    context_object_name = 'post'


# дженерик для получения деталей о товаре
class PostSearch(ListView):
    template_name = 'news/search.html'
    context_object_name = 'posts'
    queryset = Post.objects.all()

    # забираем отфильтрованные объекты переопределяя метод get_context_data у наследуемого класса 
    # (привет, полиморфизм, мы скучали!!!)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # вписываем наш фильтр в контекст
        context['filter'] = PostFilter(
            self.request.GET, queryset=self.get_queryset())
        # context['categories'] = Category.objects.all()
        context['form'] = PostForm

        return context


def page_name(r):
    req = resolve(r.path_info).kwargs['name']
    # print(req)
    return req


class PostAuthor(ListView):
    model = Post
    template_name = 'news/subcat/filtered.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        self.id = resolve(self.request.path_info).kwargs['pk']
        queryset = Post.objects.filter(author=Author.objects.get(id=self.id))

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(
            self.request.GET, queryset=self.get_queryset())
        context['name'] = Author.objects.get(authorUsername=User.objects.get(id=self.id))

        return context


class PostType(ListView):
    model = Post
    template_name = 'news/subcat/filtered.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        self.name = resolve(self.request.path_info).kwargs['name']
        queryset = Post.objects.filter(categoryType=self.name)
        return queryset


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(
            self.request.GET, queryset=self.get_queryset())
        context['name'] = self.name

        return context


class PostTag(ListView):
    model = Post
    template_name = 'news/subcat/filtered.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        self.id = resolve(self.request.path_info).kwargs['pk']
        queryset = Post.objects.filter(postCategory=Category.objects.get(id=self.id))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(
            self.request.GET, queryset=self.get_queryset())
        context['name'] = Category.objects.get(id=self.id)

        return context


class PostCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'news/crud/post_create.html'
    form_class = PostForm
    success_url = '/news/'
    permission_required = ('news.add_post')
    error_message = 'You cannot post more than 3 posts a day'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = Author.objects.get(authorUsername=self.request.user)
        postAuthor = self.object.author
        posts = Post.objects.all()
        count_todays_posts = 0 
        for post in posts:
            if post.author == postAuthor:
                time_delta = datetime.now().date() - post.dateCreated.date()
                if time_delta.total_seconds() < 86400:
                    count_todays_posts +=1

        if count_todays_posts < 3:
            self.object.save()
        
            cat = Category.objects.get(pk=self.request.POST['postCategory'])
            self.object.postCategory.add(cat)

            validated = super().form_valid(form)

        else: 
            messages.error(self.request,  'You cannot post more than 3 posts a day.')
            validated = super().form_invalid(form)

        return validated

# дженерик для редактирования объекта
class PostUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'news/crud/post_create.html'
    form_class = PostForm
    success_url = '/news/'

    permission_required = ('news.change_post')

    # метод get_object мы используем вместо queryset, чтобы получить информацию об объекте, который мы собираемся редактировать
    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        post = Post.objects.get(pk=id)
        post.isUpdated = True
        return post


# дженерик для удаления товара
class PostDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'news/crud/post_delete.html'
    success_url = '/news/'
    permission_required = ('news.delete_post')

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)


class ProfileView(ListView):
    model = CatSub
    template_name = 'news/profile.html'
    context_object_name = 'categories'


# Подписка пользователя в категорию новостей
@login_required
def subscribe_to_category(request, pk):
    user = request.user
    cat = Category.objects.get(id=pk)

    if not cat.subscribers.filter(id=user.id).exists():     
        cat.subscribers.add(user)
        html = render_to_string(
            'news/subcat/subsribed.html',
            {'categories': cat, 'user': user}, # передаем в шаблон какие захотим переменные, в данном случае я просто передал категорию для вывода ее в письме
        )  
        category = f'{cat}'
        email = user.email
        msg = EmailMultiAlternatives(
            subject=f'{category} category subscription',
            from_email='newsportal@yandex.ru',
            to=[email, ],
        ) 

        msg.attach_alternative(html, 'text/html')
        try:
            msg.send()
        except Exception as e:
            print(e)
        return redirect('/news/profile/')
        

    return redirect(request.META.get('HTTP_REFERER'))

@login_required
def unsubscribe_from_category(request, pk):
    user = request.user
    cat = Category.objects.get(id=pk)

    if cat.subscribers.filter(id=user.id).exists():     
        cat.subscribers.remove(user)        
    return redirect('/news/profile/')

news/templates/news/subcat/filtered.html
<!--наследуемся от шаблона default.html, который мы создавали ещё во времена flatpages -->
{% extends 'news/layout.html' %}
{% load custom_filters %}
<!--   Название у нас будет  -->
{% block title %} The news {% endblock title %}
<!--   block -->
{% block content %}
<!--  loop -->
<h3 class="content-subhead">
  Found
  {{filter.qs|length}} posts on query:
  <span>{{ name }}</span>
</h3>

{% if name.id %}
<div class="subscribe">
  <strong>
    Subscribe to
    <em>{{ name }}</em>?
  </strong>
  <a href="{% url 'news:sub_cat' name.id %}">
    <button class="pure-button button-success">
      <i class="bi bi-bookmark-plus"></i>
      Subscribe
    </button>
  </a>
</div>
{% endif %}

{% if is_paginated %}

<!-- Если доступна предыдущая страница, то даём ссылку на неё и самую первую страницу -->
<div class="mx-auto d-flex justify-content-center">
  <div class="pure-button-group" role="group" aria-label="...">

    {% if page_obj.has_previous %}

    <a class="page-link" href="?page=1">
      <button class="pure-button button-secondary">
        First
      </button>
    </a>
    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
      <button class="pure-button button-secondary">
        &laquo;
      </button>
    </a>

    {% endif %}

    <!-- Показываем только текущую страницу и ближайшие к ней, чтобы список не тянулся и не захламлял страницу -->
    {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
    <a class="page-link" href="#">
      <button class="pure-button button-secondary pure-button-active">
        {{ num }}
      </button>
    </a>


    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %} <a class="page-link"
      href="?page={{ num }}">
      <button class="pure-button button-secondary">
        {{ num }}
      </button>
      </a>
      {% endif %}
      {% endfor %}

      <!-- Если есть следующая страница, то даём ссылку на неё и на самую последнюю страницу -->
      {% if page_obj.has_next %}
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">
        <button class="pure-button button-secondary">
          &raquo;
        </button>
      </a>

      <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
        <button class="pure-button button-secondary">
          Last
        </button>
      </a>

      {% endif %}
  </div>
</div>
{% endif %}


<hr>

{% for n in posts %}

<!--  A single blog post -->
<section class="post">
  <header class="post-header"><img class="post-avatar" src="/{{  n.author.avatar }}" alt="avatar" />
    <a href="{% url 'news:post_view' n.id %}">
      <h2 class="post-title">{{n.title|censor}}</h2>
    </a>
    <p class="post-meta">By
      <a class="post-author" href="{% url 'news:author_name' n.author_id %}">
        {{ n.author }}
      </a>
      on
      <em>{{ n.dateCreated|date:'d M Y H:i' }}
      </em>
      Type:
      <a class="post-category post-type-{{n.categoryType}}" href="{% url 'news:post_type' n.categoryType %}">
        <span>
          {{n.get_categoryType_display}}
        </span>
      </a>
      Tags:
      {% for tag in n.postCategory.values %}
      <a class="post-category post-category-{{tag.id}}" href="{% url 'news:post_tag' tag.id %}">
        {{tag.name }}
      </a>
      {%endfor%}
    </p>
  </header>
  <div class="post-description">
    <p>{{ n.text|censor | truncatewords:25 }}</p>
    <p><em>Article rating: {{n.rating}} </em></p>
  </div>
</section>
<hr />

{%endfor%}



{% endblock content %}

news/templates/news/subcat/newpost.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Friendly Reminder</title>
</head>

<body>
  <h1>News Portal subscription</h1>
  <p>In category: <strong>"{{category_object.name}}"</strong> there is a new post by
    <strong>{{post_object.author}}</strong>.
  </p>
  <a href="https://newsportal.com{% url 'news:post_view' post_object.id %}">
    <h2>{{post_object.title}}</h2>
  </a>
  <p>{{post_object.email_preview}}</p>

</body>

</html>

news/templates/news/subcat/subsribed.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Friendly Reminder</title>
</head>

<body>
  <h1>News Portal subscription</h1>
  <p>
    <strong>{{user.username}}</strong>, you have successfully subscribed to category: "{{categories.name}}".
  </p>
</body>

</html>

news/templates/news/subcat/weekly_digest.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Weekly Digest</title>
</head>

<body>
  <h1>News Portal weekly digest</h1>
  {%for category in category_object%}
  <p>In category: <strong>"{{category}}"</strong></p>
  <p>there are new posts</p>
  {% for post in post_object %}
  {% for post_cat in post.postCategory.all %}
  {% if post_cat == category%}
  <a href="https://newsportal.com{% url 'news:post_view' post.id %}">
    <h2>
      {{post.title}}
    </h2>
  </a>
  <p>by {{post.author}}</p>
  <p>{{post.email_preview}}</p>
  {%endif%}
  {%endfor%}
  {%endfor%}
  {%endfor%}
</body>

</html>